EventIN/config/routes.rb
Rails.application.routes.draw do
  
  # Rotas de Transferencia
  get 'transfers/choice', to: 'transfers#choice', as: :transfer_choice
  post 'choice_create' => 'transfers#choice_create'
  
  # Rotas de Ranking
  get 'federacaos/ranking', to: 'federacaos#ranking', as: :ranking
  get 'ejs/ranking', to: 'ejs#ranking', as: :ranking_ejs
  
  # Rotas de escolha de palestras/workshops
  get 'workshops/choice', to: 'workshops#choice', as: :workshops_choice
  post 'workshops/submit', to: 'workshops#submit', as: :workshops_submit
  
  # Rotas de Materials
  get '/download_file', to: 'materials#download_file', as: :download_file
  
  # Rotas de escolha de quarto
  delete 'rooms/reservation', to: 'rooms#cancel_reservation', as: :cancel_reservation 
  get 'locals/choice', to: 'locals#choice', as: :local_choice
  get 'locals/rooms/:id', to: 'rooms#choice', as: :room_choice
  patch 'users/local/:id', to: 'users#reservate', as: :reservate
  
  # Recuperacao de senha
  get 'users/password_recover', to: 'users#password_recover', as: :password_recover
  post 'users/password_recover', to: 'users#set_password'
  
  resources :transfers
  resources :speakers
  resources :events
  resources :materials
  resources :workshops
  resources :rooms
  resources :locals
  resources :ejs
  resources :federacaos
  #resources :users
  
  
  # Rotas de UserController
  #get 'users/crud', to: 'users#crud', as: :crud
  get 'users', to: 'users#index', as: :users
  get 'users/new', to: 'users#new', as: :user_new
  post 'users/new', to: 'users#create'
  get 'users/:id', to: 'users#show', as: :user
  get 'users/edit/:id', to: 'users#edit', as: :user_edit
  patch 'users/edit/:id', to: 'users#update'
  delete 'users/destroy/:id', to: 'users#destroy', as: :user_destroy
  
  #Rotas de SessionsController
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy', as: :logout

end

EventIN/app/models/room.rb
class Room < ApplicationRecord
  belongs_to :local
  
  has_many :users;
end

EventIN/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  
  before_action :non_admin, except: [:choice,:show,:cancel_reservation]
  
  before_action :non_logged_user, only: [:choice,:show,:cancel_reservation]
  before_action :no_room?, only: [:choice]
  
  def cancel_reservation
    room_id = current_user.room_id
    current_user.room_id = nil
    current_user.save
    
    room = Room.find_by_id(room_id)
    room.update(:occupied => room.occupied - 1 )
    room.update(:available => true)
    
    #flash[:notice] = "Você cancelou sua reserva no quarto!"
    redirect_to local_choice_path
  end
  
  def no_room?
    if current_user.room_id
      #flash[:notice] = "Você está alocado nesse quarto!"
      redirect_to room_path(room_id)
    end
  end
  
  
  def choice
    @rooms = Room.where(local_id: params[:id], available: true)
    
    #current_user
  end
  
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:number, :capacity, :occupied, :available, :local_id)
    end
end

EventIN/app/helpers/rooms_helper.rb
module RoomsHelper
end

EventIN/app/views/rooms/_form.html.erb
<div class="topo-menu">
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>

<nav class="menu-nav">

      <%= image_tag("/assets/EventIn.png")%>
      
      <ul>
            
            <li><%= link_to 'Transferencia', transfer_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Palestras', workshops_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Hospedagens', local_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking Federação', ranking_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking EJs', ranking_ejs_path, :class=> "link-home-temp"%></li>
            
      </ul>
      
</nav>

<div class="clear"></div>

<!-- Menu -->
  <!-- background da página -->
  <section id="background-page-adm">
    <header id="menu">


    </header>

  <!-- Box do Administrador -->
    <section id="adm">
        <div class="box-adm">
        
          
        <ul>
          
          <li>  <%= link_to 'Home', login_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Recuperar Senha', password_recover_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to "Logout", logout_path, method: :delete, :class=> "link-home-temp" %>   </li>
          
          <% if current_user.admin %> 
          <li>  <%= link_to 'Transferencias', transfers_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Palestrantes', speakers_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Eventos', events_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Materiais', materials_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Quartos', rooms_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Hospedagens', locals_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'EJs', ejs_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Federações', federacaos_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Usuarios', users_path, :class=> "link-home-temp"%></li>
          <% end %>
          
        </ul>
         
        </div>
    </section> 

  <!-- Box principal -->

    <section id="principal-adm">
        <div class="box-principal-adm">
          <h1>Quartos</h1>
          
          <h2>
            <%= current_user.name %>
          </h2>
 
        <section class="box-rooms-edit">

  <div class="field-rooms">
    <!--<%= form.label :number %>-->
    <p>Numeros: </p>
    <%= form.number_field :number, id: :room_number, :class=> "text-form-cad" %>
  </div>

  <div class="field-rooms">
    <!--<%= form.label :capacity %>-->
    <p>Capacidade :</p>
    <%= form.number_field :capacity, id: :room_capacity, :class=> "text-form-cad" %>
  </div>

  <div class="field-rooms">
    <!--<%= form.label :available %>-->
    <p>Acessiveis :</p>
    <%= form.check_box :available, id: :room_available, :class=> "text-form-cad" %>
  </div>

  <div class="field-rooms">
    <!--<%= form.label :local_id %>-->
    <p>Locais :</p>
    <%= form.text_field :local_id, id: :room_local_id, :class=> "text-form-cad" %>
  </div>

  <div class="btn-rooms-edit">
    <%= form.submit %>
  </div>
<% end %>

</section>
 
        </div>
    </section>

    <div class="clear"></div>


    </section> 

    <div class="clear"></div>

  <!-- Footer -->


    <footer id="footer-materials">  
      <p>Todos os direitos reservados</p>
      <p>EventIn 2017</p>   
    </footer>
  </section>

EventIN/app/views/rooms/choice.html.erb
<nav class="menu-nav">

      <%= image_tag("/assets/EventIn.png")%>
      
      <ul>
            
            <li><%= link_to 'Transferencia', transfers_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Palestras', workshops_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Hospedagens', local_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking Federação', ranking_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking EJs', ranking_ejs_path, :class=> "link-home-temp"%></li>
            
      </ul>
      
</nav>

<div class="clear"></div>

<!-- Menu -->
  <!-- background da página -->
  <section id="background-page-adm">
    <header id="menu">


    </header>

  <!-- Box do Administrador -->
    <section id="adm">
        <div class="box-adm">
          
          <% if !current_user.admin %>
          <div class="foto-user">
            
          <%= image_tag(current_user.profile_photo_url)  if current_user.profile_photo.present? %>
          
          </div>
          <% end %>
          
        <ul>
          
          <li>  <%= link_to 'Home', login_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Recuperar Senha', password_recover_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Editar Perfil', user_edit_path(current_user), :class=> "link-home-temp" %> </li>
          <li>  <%= link_to "Logout", logout_path, method: :delete, :class=> "link-home-temp" %>   </li>
          
          
          <% if current_user.admin %> 
          <li>  <%= link_to 'Transferencias', transfers_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Palestrantes', speakers_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Eventos', events_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Materiais', materials_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Quartos', rooms_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Hospedagens', locals_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'EJs', ejs_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Federações', federacaos_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Usuarios', users_path, :class=> "link-home-temp"%></li>
          <% end %>
          
        </ul>
         
        </div>
    </section> 

  <!-- Box principal -->

    <section id="principal-adm">
        <div class="box-principal-adm">
            <h1>Quartos</h1>
            
            <div class="box-quartos">
                <div class="nome-hotel">
                  <% @rooms.each do |room| %>
                  <h3><%= room.local.name %></h3>
                </div>
                <div class="lista">
                    <h5>Número do quarto</h5>
                    <h5>Vagas</h5>
                    <h5>Vagas Ocupadas</h5>
                    <h5>Disponibilidade</h5>
                </div>
                <div class="info-quartos">
                    <p><%= room.number %></p>
                    <p><%= room.capacity %></p>
                    <p><%= room.occupied %></p>
                </div>
                <%= link_to 'Escolher', reservate_path, method: :patch, :class =>"btn-quartos" %>
            <% end %>
            </div>
            
          <p id="notice"><%= notice %></p>
 
        </div>
    </section>

    <div class="clear"></div>

  <!-- Box do ranking  -->

    <section id="ranking-adm">
        <div class="box-ranking-adm">
         
         
         
          <!--<h3>Ranking das Ejs</h3>-->
          <!--<ol>-->
          <!--  <li>  IN JUNIOR   </li>-->
          <!--  <li>  EJCM   </li>-->
          <!--  <li>  P&Q ENGENHARIA   </li>-->
          <!--</ol>-->
          
        </div>
        <div class="clear"></div>
    </section> 

    <div class="clear"></div>

  <!-- Footer -->


    <footer id="footer">  
      <p>Todos os direitos reservados</p>
      <p>EventIn 2017</p>   
    </footer>
  </section>




















<!--<p id="notice"><%= notice %></p>-->

<!--<h1>Rooms</h1>-->

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Number</th>-->
<!--      <th>Capacity</th>-->
<!--      <th>Occupied</th>-->
<!--      <th>Available</th>-->
<!--      <th>Local</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <% @rooms.each do |room| %>-->
<!--      <tr>-->
<!--        <td><%= room.number %></td>-->
<!--        <td><%= room.capacity %></td>-->
<!--        <td><%= room.occupied %></td>-->
<!--        <td><%= room.available %></td>-->
<!--        <td><%= room.local.name %></td>-->
<!--        <td><%= link_to 'Escolher', reservate_path, method: :patch %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

EventIN/app/views/rooms/edit.html.erb
<div class="topo-menu">
<h1>Editing Room</h1>
</div>
<%= render 'form', room: @room %>
<div class="topo-menu">
<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>
</div>

EventIN/app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="menu-nav">

      <%= image_tag("/assets/EventIn.png")%>
      
      <ul>
            
            <li><%= link_to 'Transferencia', transfer_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Palestras', workshops_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Hospedagens', local_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking Federação', ranking_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking EJs', ranking_ejs_path, :class=> "link-home-temp"%></li>
            
      </ul>
      
</nav>


<div class="clear"></div>

<!-- Menu -->
  <!-- background da página -->
  <section id="background-page-adm">
    <header id="menu">


    </header>

  <!-- Box do Administrador -->
    <section id="adm">
        <div class="box-adm">
        
          
        <ul>
          
          <li>  <%= link_to 'Home', login_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Recuperar Senha', password_recover_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to "Logout", logout_path, method: :delete, :class=> "link-home-temp" %>   </li>
          
          <% if current_user.admin %> 
          <li>  <%= link_to 'Transferencias', transfers_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Palestrantes', speakers_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Eventos', events_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Materiais', materials_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Quartos', rooms_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Hospedagens', locals_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'EJs', ejs_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Federações', federacaos_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Usuarios', users_path, :class=> "link-home-temp"%></li>
          <% end %>
          
        </ul>
         
        </div>
    </section> 

  <!-- Box principal -->

    <section id="principal-adm">
        <div class="box-principal-adm">
          <h1>Quartos</h1>
          
          <h2>
            <%= current_user.name %>
          </h2>
 
        <section class="box-room">
          <% @rooms.each do |room| %>
              
                <div class="desc-room"><h3>Numero : <%= room.number %></h3>
                <h3>Capacidade : <%= room.capacity %></h3>
                <h3>Ocupado : <%= room.occupied %></h3>
                <h3>Acessivel : <%= room.available %></h3>
                <h3>Local : <%= room.local.name %></h3>
                  <div class="btn-room">
                  <%= link_to 'Editar', edit_room_path(room), :class=> "link-home-temp" %>
                  <%= link_to 'Deletar', room, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "link-home-temp" %>
                  </div>
                  </div>
              
            <% end %>
            
            <%= will_paginate @rooms %> 
                  
            <div class="limpar"></div>
            
          </section>
 
        </div>
    </section>

    <div class="clear"></div>


    </section> 

    <div class="clear"></div>

  <!-- Footer -->


    <footer id="footer-room">  
      <p>Todos os direitos reservados</p>
      <p>EventIn 2017</p>   
    </footer>
  </section>

EventIN/app/views/rooms/new.html.erb
<div class="topo-menu">
<h1>New Room</h1>
</div>
<%= render 'form', room: @room %>
<div class="topo-menu">
<%= link_to 'Back', rooms_path %>
</div>

EventIN/app/views/rooms/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<nav class="menu-nav">

      <%= image_tag("/assets/EventIn.png")%><!--<img src="/assets/EventIn.png">-->

      <!--<ul>-->
      <!--  <li>  <a href="#">Home</a>   </li>-->
      <!--  <li>  <a href="#">Documentos</a>   </li>-->
      <!--  <li>  <a href="#">Criar Palestras</a>   </li>-->
      <!--  <li>  <a href="#">Criar Eventos</a>   </li>-->
      <!--  <li>  <a href="#">Criar Hospedagens</a>   </li>-->
      <!--  <li>  <a href="#">Criar EJs e Federações</a>   </li>-->
      <!--</ul>-->
      
      <ul>
            
            <li><%= link_to 'Transferencia', transfers_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Palestras', workshops_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Hospedagens', local_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking Federação', ranking_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking EJs', ranking_ejs_path, :class=> "link-home-temp"%></li>
      </ul>
      
</nav>

<div class="clear"></div>

<!-- Menu -->
  <!-- background da página -->
  <section id="background-page-adm">
    <header id="menu">


    </header>

  <!-- Box do Administrador -->
    <section id="adm">
        <div class="box-adm">
          
          <% if !current_user.admin %>
          <div class="foto-user">
            
          <%= image_tag(current_user.profile_photo_url)  if current_user.profile_photo.present? %>
          
          </div>
          <% end %>
          
        <ul>
          
          <li>  <%= link_to 'Home', login_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Editar Perfil', user_edit_path(current_user), :class=> "link-home-temp" %> </li>
          <li>  <%= link_to "Logout", logout_path, method: :delete, :class=> "link-home-temp" %>   </li>
          
          <% if current_user.admin %> 
          <li>  <%= link_to 'Criar Evento', new_event_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Documentos', new_material_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Palestras', new_workshop_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Quarto', new_room_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Hospedagem', new_local_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar EJS', new_ej_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Federação', new_federacao_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Usuarios', users_path, :class=> "link-home-temp"%> </li>
          <% end %>
          
        </ul>
         
        </div>
    </section> 

  <!-- Box principal -->

    <section id="principal-adm">
        <div class="box-principal-adm">
          
          <h1>Reserva de Hotel</h1>
              
          <div class="box-confirmation">
                <%= image_tag("/assets/hotel1.jpg") %>
                <div class="titulo-confirmation">
                      <h3><%= @room.local.name %></h3>
                </div>
                <div class="tags-confirmation1">
                      <h5>Número do Quarto</h5>
                      <p><%= @room.number %></p>
                </div>
                <div class="tags-confirmation2">
                      <h5>Vagas Disponíveis</h5>
                      <p><%= @room.capacity %></p>
                </div>
                <div class="tags-confirmation3">
                      <h5>Vagas Ocupadas</h5>
                      <p><%= @room.occupied %></p>
                </div>
                <%= link_to 'Cancelar reserva', cancel_reservation_path, method: :delete, :class=> "btn-confirmation" %>
                
          </div>
                  
                  
     
 
          
 
        </div>
    </section>

    <div class="clear"></div>

  <!-- Box do ranking  -->

    <section id="ranking-adm">
        <div class="box-ranking-adm">
         
         
         
          <!--<h3>Ranking das Ejs</h3>-->
          <!--<ol>-->
          <!--  <li>  IN JUNIOR   </li>-->
          <!--  <li>  EJCM   </li>-->
          <!--  <li>  P&Q ENGENHARIA   </li>-->
          <!--</ol>-->
          
        </div>
        <div class="clear"></div>
    </section> 

    <div class="clear"></div>

  <!-- Footer -->


    <footer id="footer">  
      <p>Todos os direitos reservados</p>
      <p>EventIn 2017</p>   
    </footer>
  </section>


















<!--<p id="notice"><%= notice %></p>-->

<!--<p>-->
<!--  <strong>Number:</strong>-->
<!--  <%= @room.number %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Capacity:</strong>-->
<!--  <%= @room.capacity %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Occupied:</strong>-->
<!--  <%= @room.occupied %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Available:</strong>-->
<!--  <%= @room.available %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Local:</strong>-->
<!--  <%= @room.local.name %>-->
<!--</p>-->

<!--<% if current_user.room_id == @room.id %>-->
<!--  <%= link_to 'Cancelar reserva', cancel_reservation_path, method: :delete %> |-->
<!--<% end %>-->

<!--<%= link_to 'Edit', edit_room_path(@room) %> |-->
<!--<%= link_to 'Back', rooms_path %>-->