EventIN/config/routes.rb
Rails.application.routes.draw do
  
  # Rotas de Transferencia
  get 'transfers/choice', to: 'transfers#choice', as: :transfer_choice
  post 'choice_create' => 'transfers#choice_create'
  
  # Rotas de Ranking
  get 'federacaos/ranking', to: 'federacaos#ranking', as: :ranking
  get 'ejs/ranking', to: 'ejs#ranking', as: :ranking_ejs
  
  # Rotas de escolha de palestras/workshops
  get 'workshops/choice', to: 'workshops#choice', as: :workshops_choice
  post 'workshops/submit', to: 'workshops#submit', as: :workshops_submit
  
  # Rotas de Materials
  get '/download_file', to: 'materials#download_file', as: :download_file
  
  # Rotas de escolha de quarto
  delete 'rooms/reservation', to: 'rooms#cancel_reservation', as: :cancel_reservation 
  get 'locals/choice', to: 'locals#choice', as: :local_choice
  get 'locals/rooms/:id', to: 'rooms#choice', as: :room_choice
  patch 'users/local/:id', to: 'users#reservate', as: :reservate
  
  # Recuperacao de senha
  get 'users/password_recover', to: 'users#password_recover', as: :password_recover
  post 'users/password_recover', to: 'users#set_password'
  
  resources :transfers
  resources :speakers
  resources :events
  resources :materials
  resources :workshops
  resources :rooms
  resources :locals
  resources :ejs
  resources :federacaos
  #resources :users
  
  
  # Rotas de UserController
  #get 'users/crud', to: 'users#crud', as: :crud
  get 'users', to: 'users#index', as: :users
  get 'users/new', to: 'users#new', as: :user_new
  post 'users/new', to: 'users#create'
  get 'users/:id', to: 'users#show', as: :user
  get 'users/edit/:id', to: 'users#edit', as: :user_edit
  patch 'users/edit/:id', to: 'users#update'
  delete 'users/destroy/:id', to: 'users#destroy', as: :user_destroy
  
  #Rotas de SessionsController
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy', as: :logout

end

EventIN/app/models/local.rb
class Local < ApplicationRecord
  mount_uploader :photo, PictureUploader
  
  has_many :rooms;
end

EventIN/app/controllers/locals_controller.rb
class LocalsController < ApplicationController
  before_action :set_local, only: [:show, :edit, :update, :destroy]
    
  before_action :non_admin, except: [:choice,:show]
  before_action :non_logged_user, only: [:choice,:show]
  
  before_action :no_room?, only: [:choice]
  
  def no_room?
    if current_user.room_id
      flash[:notice] = "Você está alocado nesse quarto!"
      redirect_to room_path(current_user.room_id)
    end
  end
  
  def choice
    #@locals = Local.where(Room.find_by_local_id())
    @locals = Local.paginate(:page => params[:page], :per_page => 2)
  end
  
  # GET /locals
  # GET /locals.json
  def index
    #@locals = Local.all
    @locals = Local.paginate(:page => params[:page], :per_page => 10)
  end
  
  # GET /locals/1
  # GET /locals/1.json
  def show
  end

  # GET /locals/new
  def new
    @local = Local.new
  end

  # GET /locals/1/edit
  def edit
  end

  # POST /locals
  # POST /locals.json
  def create
    @local = Local.new(local_params)

    respond_to do |format|
      if @local.save
        format.html { redirect_to @local, notice: 'Local was successfully created.' }
        format.json { render :show, status: :created, location: @local }
      else
        format.html { render :new }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locals/1
  # PATCH/PUT /locals/1.json
  def update
    respond_to do |format|
      if @local.update(local_params)
        format.html { redirect_to @local, notice: 'Local was successfully updated.' }
        format.json { render :show, status: :ok, location: @local }
      else
        format.html { render :edit }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locals/1
  # DELETE /locals/1.json
  def destroy
    @local.destroy
    respond_to do |format|
      format.html { redirect_to locals_url, notice: 'Local was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local
      @local = Local.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def local_params
      params.require(:local).permit(:name, :address, :photo)
    end
end

EventIN/app/helpers/locals_helper.rb
module LocalsHelper
end

EventIN/app/views/locals/_form.html.erb
<div class="topo-menu">
<%= form_with(model: local, local: true) do |form| %>
  <% if local.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(local.errors.count, "error") %> prohibited this local from being saved:</h2>

      <ul>
      <% local.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>


<nav class="menu-nav">

      <%= image_tag("/assets/EventIn.png")%>
      
      <ul>
            
            <li><%= link_to 'Transferencia', transfer_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Palestras', workshops_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Hospedagens', local_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking Federação', ranking_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking EJs', ranking_ejs_path, :class=> "link-home-temp"%></li>
            
      </ul>
      
</nav>

<div class="clear"></div>

<!-- Menu -->
  <!-- background da página -->
  <section id="background-page-adm">
    <header id="menu">


    </header>

  <!-- Box do Administrador -->
    <section id="adm">
        <div class="box-adm">
        
          
        <ul>
          
          <li>  <%= link_to 'Home', login_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Recuperar Senha', password_recover_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to "Logout", logout_path, method: :delete, :class=> "link-home-temp" %>   </li>
          
          <% if current_user.admin %> 
          <li>  <%= link_to 'Transferencias', transfers_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Palestrantes', speakers_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Eventos', events_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Materiais', materials_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Quartos', rooms_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Hospedagens', locals_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'EJs', ejs_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Federações', federacaos_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Usuarios', users_path, :class=> "link-home-temp"%></li>
          <% end %>
          
        </ul>
         
        </div>
    </section> 

  <!-- Box principal -->

    <section id="principal-adm">
        <div class="box-principal-adm">
          <h1>Hospedagens</h1>
          
          <h2>
            <%= current_user.name %>
          </h2>
 
        <section class="box-locals-edit">

 <div class="field-locals">
    <!--<%= form.label :name %>-->
    <p>Nome: </p>
    <%= form.text_field :name, id: :local_name, :class=> "text-form-cad" %>
  </div>

  <div class="field-locals">
    <!--<%= form.label :address %>-->
    <p>Endereço: </p>
    <%= form.text_field :address, id: :local_address, :class=> "text-form-cad" %>
  </div>

  <div class="btn-locals-edit">
    <%= form.submit %>
  </div>
<% end %>



</section>
 
        </div>
    </section>

    <div class="clear"></div>


    </section> 

    <div class="clear"></div>

  <!-- Footer -->


    <footer id="footer-materials">  
      <p>Todos os direitos reservados</p>
      <p>EventIn 2017</p>   
    </footer>
  </section>

EventIN/app/views/locals/choice.html.erb
<!--<p id="notice"><%= notice %></p>-->

<nav class="menu-nav">

      <%= image_tag("/assets/EventIn.png")%>
      
      <ul>
            
            <li><%= link_to 'Transferencia', transfers_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Palestras', workshops_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Hospedagens', local_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking Federação', ranking_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking EJs', ranking_ejs_path, :class=> "link-home-temp"%></li>
            
      </ul>
      
</nav>

<div class="clear"></div>

<!-- Menu -->
  <!-- background da página -->
  <section id="background-page-adm">
    <header id="menu">


    </header>

  <!-- Box do Administrador -->
    <section id="adm">
        <div class="box-adm">
          
          <% if !current_user.admin %>
          <div class="foto-user">
            
          <%= image_tag(current_user.profile_photo_url)  if current_user.profile_photo.present? %>
          
          </div>
          <% end %>
          
        <ul>
          
          <li>  <%= link_to 'Home', login_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Recuperar Senha', password_recover_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Editar Perfil', user_edit_path(current_user), :class=> "link-home-temp" %> </li>
          <li>  <%= link_to "Logout", logout_path, method: :delete, :class=> "link-home-temp" %>   </li>
          
          
          <% if current_user.admin %> 
          <li>  <%= link_to 'Transferencias', transfers_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Palestrantes', speakers_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Eventos', events_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Materiais', materials_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Quartos', rooms_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Hospedagens', locals_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'EJs', ejs_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Federações', federacaos_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Usuarios', users_path, :class=> "link-home-temp"%></li>
          <% end %>
          
        </ul>
         
        </div>
    </section> 

  <!-- Box principal -->

    <section id="principal-adm">
        <div class="box-principal-adm">
          
          <h1>Hotéis</h1>
          
          <section id="box-hoteis">
              <% @locals.each do |local| %>
              <div class="box-hoteis">
                  <%= image_tag("/assets/hotel1.jpg") %>
                  <div class="titulo">
                      <h3><%= local.name %></h3>
                      <p><%= local.address %></p>
                  </div>
                  <%= link_to 'Ver quartos', room_choice_path(local.id), :class =>"btn-hotel" %>
                  
                  
              </div>
              <% end %>
              
              <%= will_paginate @locals %>
          </section>
 
          
 
        </div>
    </section>

    <div class="clear"></div>

  <!-- Box do ranking  -->

    <section id="ranking-adm">
        <div class="box-ranking-adm">
         
         
         
          <!--<h3>Ranking das Ejs</h3>-->
          <!--<ol>-->
          <!--  <li>  IN JUNIOR   </li>-->
          <!--  <li>  EJCM   </li>-->
          <!--  <li>  P&Q ENGENHARIA   </li>-->
          <!--</ol>-->
          
        </div>
        <div class="clear"></div>
    </section> 

    <div class="clear"></div>

  <!-- Footer -->


    <footer id="footer">  
      <p>Todos os direitos reservados</p>
      <p>EventIn 2017</p>   
    </footer>
  </section>


















<!--<p id="notice"><%= notice %></p>-->

<!--<h1>Locais</h1>-->

<!--<table id="locals_choice_adm">-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Nome</th>-->
<!--      <th>Endereço</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <% @locals.each do |local| %>-->
<!--      <tr>-->
<!--        <td><%= local.name %></td>-->
<!--        <td><%= local.address %></td>-->
<!--        <td><%= link_to 'Ver quartos', room_choice_path(local.id) %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

<!--<div class="navPag">-->
<!--  <%= will_paginate @locals %>-->
<!--</div>-->
<!--<script>-->
<!--  $('#locals_choice_adm').DataTable({});-->
<!--</script>-->

EventIN/app/views/locals/edit.html.erb
<div class="topo-menu">
<h1>Editing Local</h1>
</div>
<%= render 'form', local: @local %>
<div class="topo-menu">
<%= link_to 'Show', @local %> |
<%= link_to 'Back', locals_path %>
</div>

EventIN/app/views/locals/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="menu-nav">

      <%= image_tag("/assets/EventIn.png")%>
      
      <ul>
            
            <li><%= link_to 'Transferencia', transfer_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Palestras', workshops_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Hospedagens', local_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking Federação', ranking_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking EJs', ranking_ejs_path, :class=> "link-home-temp"%></li>
            
      </ul>
      
</nav>

<div class="clear"></div>

<!-- Menu -->
  <!-- background da página -->
  <section id="background-page-adm">
    <header id="menu">


    </header>

  <!-- Box do Administrador -->
    <section id="adm">
        <div class="box-adm">
        
          
<ul>
          
          <li>  <%= link_to 'Home', login_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Recuperar Senha', password_recover_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to "Logout", logout_path, method: :delete, :class=> "link-home-temp" %>   </li>
          
          <% if current_user.admin %> 
          <li>  <%= link_to 'Transferencias', transfers_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Palestrantes', speakers_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Eventos', events_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Materiais', materials_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Quartos', rooms_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Hospedagens', locals_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'EJs', ejs_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Federações', federacaos_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Usuarios', users_path, :class=> "link-home-temp"%></li>
          <% end %>
          
        </ul>
         
        </div>
    </section> 

  <!-- Box principal -->

    <section id="principal-adm">
        <div class="box-principal-adm">
          <h1>Hospedagens</h1>
          
          <h2>
            <%= current_user.name %>
          </h2>
 
        <section class="box-locals">
             <% @locals.each do |local| %>

                <div class="desc-locals"><h3>Nome : <%= local.name %></h3>
                <h3>Endereço : <%= local.address %></h3>
                <div class="btn-locals"><%= link_to 'Editar', edit_local_path(local), :class=> "link-home-temp" %>
                <%= link_to 'Deletar', local, method: :delete, data: { confirm: 'Você Tem cereteza disso?' }, :class=> "link-home-temp" %>
                </div>
                </div>
              
            <% end %>
            
            <%= will_paginate @locals %> 
          </section>
 
        </div>
    </section>

    <div class="clear"></div>


    </section> 

    <div class="clear"></div>

  <!-- Footer -->


    <footer id="footer-locals">  
      <p>Todos os direitos reservados</p>
      <p>EventIn 2017</p>   
    </footer>
  </section>





<script>
  $('#locals_adm').DataTable({});
</script>

EventIN/app/views/locals/new.html.erb
<div class="topo-menu">
<h1>New Local</h1>
</div>
<%= render 'form', local: @local %>
<div class="topo-menu">
<%= link_to 'Back', locals_path %>
</div>

EventIN/app/views/locals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @local.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @local.address %>
</p>

<%= link_to 'Edit', edit_local_path(@local) %> |
<%= link_to 'Back', locals_path %>