EventIN/config/routes.rb
Rails.application.routes.draw do
  
  # Rotas de Transferencia
  get 'transfers/choice', to: 'transfers#choice', as: :transfer_choice
  post 'choice_create' => 'transfers#choice_create'
  
  # Rotas de Ranking
  get 'federacaos/ranking', to: 'federacaos#ranking', as: :ranking
  get 'ejs/ranking', to: 'ejs#ranking', as: :ranking_ejs
  
  # Rotas de escolha de palestras/workshops
  get 'workshops/choice', to: 'workshops#choice', as: :workshops_choice
  post 'workshops/submit', to: 'workshops#submit', as: :workshops_submit
  
  # Rotas de Materials
  get '/download_file', to: 'materials#download_file', as: :download_file
  
  # Rotas de escolha de quarto
  delete 'rooms/reservation', to: 'rooms#cancel_reservation', as: :cancel_reservation 
  get 'locals/choice', to: 'locals#choice', as: :local_choice
  get 'locals/rooms/:id', to: 'rooms#choice', as: :room_choice
  patch 'users/local/:id', to: 'users#reservate', as: :reservate
  
  # Recuperacao de senha
  get 'users/password_recover', to: 'users#password_recover', as: :password_recover
  post 'users/password_recover', to: 'users#set_password'
  
  resources :transfers
  resources :speakers
  resources :events
  resources :materials
  resources :workshops
  resources :rooms
  resources :locals
  resources :ejs
  resources :federacaos
  #resources :users
  
  
  # Rotas de UserController
  #get 'users/crud', to: 'users#crud', as: :crud
  get 'users', to: 'users#index', as: :users
  get 'users/new', to: 'users#new', as: :user_new
  post 'users/new', to: 'users#create'
  get 'users/:id', to: 'users#show', as: :user
  get 'users/edit/:id', to: 'users#edit', as: :user_edit
  patch 'users/edit/:id', to: 'users#update'
  delete 'users/destroy/:id', to: 'users#destroy', as: :user_destroy
  
  #Rotas de SessionsController
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy', as: :logout

end

EventIN/app/models/workshop.rb
class Workshop < ApplicationRecord
  belongs_to :speaker #palestrante
  
  has_many :materials
  
  has_many :user_workshops; #uma palestra/workshop pode ter diversos usuarios inscritos
end

EventIN/app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show, :edit, :update, :destroy]
  
  before_action :non_admin, except: [:index,:choice,:submit,:show]
  
  def submit
    adicionar = params[:listaAdicionar]
    remover = params[:listaRemover]
    
    if adicionar 
      for id_workshop in adicionar
        u = UserWorkshop.new
        u.workshop_id = id_workshop
        u.user_id = current_user.id
        
        if u.save
          w = Workshop.find_by_id(id_workshop)
          w.occupied = w.occupied + 1
          if (w.occupied == w.capacity)
            w.available = false
          end
          
          w.save
        end
        
      end
    end
    
    if remover
      for id_workshop in remover
        UserWorkshop.where(:user_id => current_user.id,:workshop_id => id_workshop).destroy_all
        
        w = Workshop.find_by_id(id_workshop)
        w.update(:occupied => w.occupied - 1)
        w.update(:available => true)
      end
    end
  end
  
  def choice
    @workshops = Workshop.paginate(:page => params[:page], :per_page => 10)
  end
  
  # GET /workshops
  # GET /workshops.json
  def index
    #@workshops = Workshop.all
    @workshops = Workshop.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
    @materials = Material.where(:workshop_id => params[:id])
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /workshops/1/edit
  def edit
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = Workshop.new(workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render :new }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(:title, :description, :begin_time, :finish_time, :capacity, :occupied, :available, :local, :speaker_id)
    end
end

EventIN/app/helpers/workshops_helper.rb
module WorkshopsHelper
end

EventIN/app/views/workshops/_form.html.erb
<div class="topo-menu">
<%= form_with(model: workshop, local: true) do |form| %>
  <% if workshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

      <ul>
      <% workshop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>

<nav class="menu-nav">

      <%= image_tag("/assets/EventIn.png")%><!--<img src="/assets/EventIn.png">-->

      <ul>
            
            <li>  <%= link_to 'Evento', events_path, :class=> "link-home-temp"%>   </li>
            <li>  <%= link_to 'Downloads', materials_path, :class=> "link-home-temp"%>   </li>
            <li>  <%= link_to 'Palestras', workshops_path, :class=> "link-home-temp"%>   </li>
           
            <li>  <%= link_to 'Hospedagens', local_choice_path, :class=> "link-home-temp"%>   </li>
            <li>  <%= link_to 'EJS', ejs_path, :class=> "link-home-temp"%>   </li>
            <li>  <%= link_to 'Federações', federacaos_path, :class=> "link-home-temp"%>   </li>
      </ul>
      
</nav>

<div class="clear"></div>

<!-- Menu -->
  <!-- background da página -->
  <section id="background-page-adm">
    <header id="menu">


    </header>

  <!-- Box do Administrador -->
    <section id="adm">
        <div class="box-adm">
        
          
        <ul>
          
          <li>  <%= link_to 'Home', login_path, :class=> "link-home-temp"%></li>

          <li>  <%= link_to "Logout", logout_path, method: :delete, :class=> "link-home-temp" %>   </li>
          
          <% if current_user.admin %> 
          <li>  <%= link_to 'Criar Evento', new_event_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Documentos', new_material_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Palestras', new_workshop_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Quarto', new_room_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Hospedagem', new_local_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar EJS', new_ej_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Federação', new_federacao_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Usuarios', users_path, :class=> "link-home-temp"%> </li>
          <% end %>
          
        </ul>
         
        </div>
    </section> 

  <!-- Box principal -->

    <section id="principal-adm">
        <div class="box-principal-adm">
          <h1>Palestras</h1>
          
          <h2>
            <%= current_user.name %>
          </h2>
 
        <section class="box-workshops-edit">


            <div class="field-workshops">
              <!--<%= form.label :title %>-->
              <p>Titulo : </p>
              <%= form.text_field :title, id: :workshop_title, :class=> "text-form-cad" %>
            </div>
          
            <div class="field-workshops">
              <!--<%= form.label :description %>-->
              <p>Descrição : </p>
              <%= form.text_area :description, id: :workshop_description, :class=> "text-form-cad" %>
            </div>
          
            <div class="field-workshops">
              <!--<%= form.label :begin_time %>-->
              <p>Inicio do Tempo : </p>
              <%= form.datetime_select :begin_time, id: :workshop_begin_time, :class=> "text-form-cad" %>
            </div>
          
            <div class="field-workshops">
              <!--<%= form.label :finish_time %>-->
              <p>Fim do Tempo : </p>
              <%= form.datetime_select :finish_time, id: :workshop_finish_time, :class=> "text-form-cad" %>
            </div>
          
            <div class="field-workshops">
              <!--<%= form.label :capacity %>-->
              <p>Capacidade : </p>
              <%= form.number_field :capacity, id: :workshop_capacity, :class=> "text-form-cad" %>
            </div>
          
            <div class="field-workshops">
              <!--<%= form.label :available %>-->
              <p>Disponivel : </p>
              <%= form.check_box :available, id: :workshop_available, :class=> "text-form-cad" %>
            </div>
          
            <div class="field-workshops">
              <!--<%= form.label :local %>-->
              <p>Local : </p>
              <%= form.text_field :local, id: :workshop_local, :class=> "text-form-cad" %>
            </div>
          
            <div class="field-workshops-palestrantes">
              <!--<%= form.label :speaker_id %>-->
              <p>Palestrantes : </p>
              <%= form.text_field :speaker_id, id: :workshop_speaker_id, :class=> "text-form-cad" %>
            </div>
          
            <div class="btn-workshops-edit">
              <%= form.submit %>
            </div>
          <% end %>


          </section>
 
        </div>
    </section>

    <div class="clear"></div>


    </section> 

    <div class="clear"></div>

  <!-- Footer -->


    <footer id="footer-workshops">  
      <p>Todos os direitos reservados</p>
      <p>EventIn 2017</p>   
    </footer>
  </section>

EventIN/app/views/workshops/choice.html.erb
<nav class="menu-nav">

      <%= image_tag("/assets/EventIn.png")%>
      
      <ul>
            
            <li><%= link_to 'Transferencia', transfers_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Palestras', workshops_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Hospedagens', local_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking Federação', ranking_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking EJs', ranking_ejs_path, :class=> "link-home-temp"%></li>
            
      </ul>
      
</nav>

<div class="clear"></div>

<!-- Menu -->
  <!-- background da página -->
  <section id="background-page-adm">
    <header id="menu">


    </header>

  <!-- Box do Administrador -->
    <section id="adm">
        <div class="box-adm">
          
          <% if !current_user.admin %>
          <div class="foto-user">
            
          <%= image_tag(current_user.profile_photo_url)  if current_user.profile_photo.present? %>
          
          </div>
          <% end %>
          
         <ul>
          
          <li>  <%= link_to 'Home', login_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Recuperar Senha', password_recover_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Editar Perfil', user_edit_path(current_user), :class=> "link-home-temp" %> </li>
          <li>  <%= link_to "Logout", logout_path, method: :delete, :class=> "link-home-temp" %>   </li>
          
          
          <% if current_user.admin %> 
          <li>  <%= link_to 'Transferencias', transfers_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Palestrantes', speakers_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Eventos', events_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Materiais', materials_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Quartos', rooms_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Hospedagens', locals_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'EJs', ejs_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Federações', federacaos_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Usuarios', users_path, :class=> "link-home-temp"%></li>
          <% end %>
          
        </ul>
         
        </div>
    </section> 

  <!-- Box principal -->

    <section id="principal-adm">
        <div class="box-principal-adm">
            <h1>Workshops</h1>
            <% @workshops.each do |workshop| %>
            <div class="box-workshops">
                <p class="titulo"><%= workshop.title %></p>
                <p class="tags">Palestrante</p>
                <p class="campos"><%= Speaker.find_by_id(workshop.speaker_id).name %></p>
                <p class="tags">Descrição</p>
                <p class="campos"><%= workshop.description %></p>
                <p class="tags">Horário</p>
                <p class="campos"><%= workshop.begin_time %> ás <%= workshop.finish_time %></p>
                <p class="tags">Capacidade   Ocupação</p>
                <p class="campos"><%= workshop.capacity %>  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  <%= workshop.occupied %></p>
                <p class="tags">Local</p>
                <p class="campos"><%= workshop.local %></p>
                <p class="btn-ins">Inscrever-se &nbsp; <input class="inscricao" type="checkbox" value= "<%= workshop.id %>" <%= 'checked' if inscritoNaPalestra(current_user, workshop)%> ></p>
                <%= link_to 'VER', workshop, :class=> "btn-show"%>
            </div>
            
            <%= will_paginate @workshops %> 
            
            <% end %>
 
          
 
        </div>
    </section>

    <div class="clear"></div>

  <!-- Box do ranking  -->

    <section id="ranking-adm">
        <div class="box-ranking-adm">
         
         
         
          <!--<h3>Ranking das Ejs</h3>-->
          <!--<ol>-->
          <!--  <li>  IN JUNIOR   </li>-->
          <!--  <li>  EJCM   </li>-->
          <!--  <li>  P&Q ENGENHARIA   </li>-->
          <!--</ol>-->
          
        </div>
        <div class="clear"></div>
    </section> 

    <div class="clear"></div>

  <!-- Footer -->


    <footer id="footer">  
      <p>Todos os direitos reservados</p>
      <p>EventIn 2017</p>   
    </footer>
  </section>


















<!--<p id="notice"><%= notice %></p>-->

<!--<h1>Workshops</h1>-->

<!--<table id="workshops">-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Title</th>-->
<!--      <th>Description</th>-->
<!--      <th>Begin time</th>-->
<!--      <th>Finish time</th>-->
<!--      <th>Capacity</th>-->
<!--      <th>Occupied</th>-->
<!--      <th>Available</th>-->
<!--      <th>Local</th>-->
<!--      <th>Palestrante</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <% @workshops.each do |workshop| %>-->
<!--      <tr>-->
<!--        <td><%= workshop.title %></td>-->
<!--        <td><%= workshop.description %></td>-->
<!--        <td><%= workshop.begin_time %></td>-->
<!--        <td><%= workshop.finish_time %></td>-->
<!--        <td><%= workshop.capacity %></td>-->
<!--        <td><%= workshop.occupied %></td>-->
<!--        <td><%= workshop.available %></td>-->
<!--        <td><%= workshop.local %></td>-->
<!--        <td><%= Speaker.find_by_id(workshop.speaker_id).name %></td>-->
        
<!--        <td> <input class="inscricao" type="checkbox" value= "<%= workshop.id %>" <%= 'checked' if inscritoNaPalestra(current_user, workshop)%> >-->
<!--        </td>-->
        
<!--        <td><%= link_to 'Show', workshop %></td>-->
<!--        <td><%= link_to 'Edit', edit_workshop_path(workshop) %></td>-->
<!--        <td><%= link_to 'Destroy', workshop, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
<!--</table>-->

<!--<button class = 'btn_inscrever'>Confirmar</button>-->

<!--<br>-->

<!--<%= link_to 'New Workshop', new_workshop_path %>-->

<!--<div class="navPag">-->
<!--  <%= will_paginate @workshops %>-->
<!--</div>-->
<script>
  $('#workshops').DataTable({});
</script>

EventIN/app/views/workshops/edit.html.erb
<div class="topo-menu">
<h1>Editing Workshop</h1>
</div>
<%= render 'form', workshop: @workshop %>
<div class="topo-menu">
<%= link_to 'Show', @workshop %> |
<%= link_to 'Back', workshops_path %>
</div>

EventIN/app/views/workshops/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="menu-nav">

      <%= image_tag("/assets/EventIn.png")%><!--<img src="/assets/EventIn.png">-->

      <ul>
            
            <li>  <%= link_to 'Evento', events_path, :class=> "link-home-temp"%>   </li>
            <li>  <%= link_to 'Downloads', materials_path, :class=> "link-home-temp"%>   </li>
            <li>  <%= link_to 'Palestras', workshops_path, :class=> "link-home-temp"%>   </li>
           
            <li>  <%= link_to 'Hospedagens', local_choice_path, :class=> "link-home-temp"%>   </li>
            <li>  <%= link_to 'EJS', ejs_path, :class=> "link-home-temp"%>   </li>
            <li>  <%= link_to 'Federações', federacaos_path, :class=> "link-home-temp"%>   </li>
      </ul>
      
</nav>

<div class="clear"></div>

<!-- Menu -->
  <!-- background da página -->
  <section id="background-page-adm">
    <header id="menu">


    </header>

  <!-- Box do Administrador -->
    <section id="adm">
        <div class="box-adm">
        
          
        <ul>
          
          <li>  <%= link_to 'Home', login_path, :class=> "link-home-temp"%></li>

          <li>  <%= link_to "Logout", logout_path, method: :delete, :class=> "link-home-temp" %>   </li>
          
          <% if current_user.admin %> 
          <li>  <%= link_to 'Criar Evento', new_event_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Documentos', new_material_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Palestras', new_workshop_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Quarto', new_room_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Hospedagem', new_local_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar EJS', new_ej_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Federação', new_federacao_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Usuarios', users_path, :class=> "link-home-temp"%> </li>
          <% end %>
          
        </ul>
         
        </div>
    </section> 

  <!-- Box principal -->

    <section id="principal-adm">
        <div class="box-principal-adm">
          <h1>Palestras</h1>
          
          <h2>
            <%= current_user.name %>
          </h2>
 
        <section class="box-workshops">
            <% @workshops.each do |workshop| %>
              
                <div class="desc-workshops">
                <h3>Titulo :<%= workshop.title %></h3>
                <h3>Descrição :<%= workshop.description %></h3>
                <h3>Inicio do Tempo :<%= workshop.begin_time %></h3>
                <h3>Fim do Tempo :<%= workshop.finish_time %></h3>
                <h3>Capacidade :<%= workshop.capacity %></h3>
                <h3>Ocupado :<%= workshop.occupied %></h3>
                <h3>Disponivel :<%= workshop.available %></h3>
                <h3>Local :<%= workshop.local %></h3>
                <h3>Palestrante :<%= Speaker.find_by_id(workshop.speaker_id).name %></h3>
                
                <div class="btn-workshops"><%= link_to 'Editar', edit_workshop_path(workshop), :class=> "link-workshop" %>
                <%= link_to 'Deletar', workshop, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "link-workshop" %>
                
                </div>
                
                <%= will_paginate @workshops %> 
                
                </div>

                

           <% end %>     
            
           
           
          </section>
           
        </div>
    </section>

    <div class="clear"></div>


    </section> 

    <div class="clear"></div>

  <!-- Footer -->


    <footer id="footer-workshops">  
      <p>Todos os direitos reservados</p>
      <p>EventIn 2017</p>   
    </footer>
  </section>

<script>
  $('#workshops_adm').DataTable({});
</script>

EventIN/app/views/workshops/new.html.erb
<div class="topo-menu">
<h1>New Workshop</h1>
</div>
<%= render 'form', workshop: @workshop %>
<div class="topo-menu">
<%= link_to 'Back', workshops_path %>
</div>

EventIN/app/views/workshops/show.html.erb
<nav class="menu-nav">

      <%= image_tag("/assets/EventIn.png")%><!--<img src="/assets/EventIn.png">-->

      <!--<ul>-->
      <!--  <li>  <a href="#">Home</a>   </li>-->
      <!--  <li>  <a href="#">Documentos</a>   </li>-->
      <!--  <li>  <a href="#">Criar Palestras</a>   </li>-->
      <!--  <li>  <a href="#">Criar Eventos</a>   </li>-->
      <!--  <li>  <a href="#">Criar Hospedagens</a>   </li>-->
      <!--  <li>  <a href="#">Criar EJs e Federações</a>   </li>-->
      <!--</ul>-->
      
      <ul>
            
            <li><%= link_to 'Transferencia', transfers_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Palestras', workshops_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Hospedagens', local_choice_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking Federação', ranking_path, :class=> "link-home-temp"%></li>
            <li><%= link_to 'Ranking EJs', ranking_ejs_path, :class=> "link-home-temp"%></li>
      </ul>
      
</nav>

<div class="clear"></div>

<!-- Menu -->
  <!-- background da página -->
  <section id="background-page-adm">
    <header id="menu">


    </header>

  <!-- Box do Administrador -->
    <section id="adm">
        <div class="box-adm">
          
          <% if !current_user.admin %>
          <div class="foto-user">
            
          <%= image_tag(current_user.profile_photo_url)  if current_user.profile_photo.present? %>
          
          </div>
          <% end %>
          
        <ul>
          
          <li>  <%= link_to 'Home', login_path, :class=> "link-home-temp"%></li>
          <li>  <%= link_to 'Editar Perfil', user_edit_path(current_user), :class=> "link-home-temp" %> </li>
          <li>  <%= link_to "Logout", logout_path, method: :delete, :class=> "link-home-temp" %>   </li>
          
          <% if current_user.admin %> 
          <li>  <%= link_to 'Criar Evento', new_event_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Documentos', new_material_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Palestras', new_workshop_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Quarto', new_room_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Hospedagem', new_local_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar EJS', new_ej_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Criar Federação', new_federacao_path, :class=> "link-home-temp"%> </li>
          <li>  <%= link_to 'Usuarios', users_path, :class=> "link-home-temp"%> </li>
          <% end %>
          
        </ul>
         
        </div>
    </section> 

  <!-- Box principal -->

    <section id="principal-adm">
        <div class="box-principal-adm">
            <h1>Workshops</h1>
            <div class="box-details">
                <p class="titulo"><%= @workshop.title %></p>
                <p class="tags">Palestrante</p>
                <p class="campos"><%= @workshop.speaker.name %></p>
                <p class="tags">Descrição</p>
                <p class="campos"><%= @workshop.description %></p>
                <p class="tags">Materiais Necessários</p>
                <% @materials.each do |material| %>
                    <div class="materiais">
                        <p class="arq">Arquivo</p>
                        <p class="desc">Descrição</p>
                        <p class="materiais-titulo"><%= material.title %></p>
                        <p class="materiais-descricao"><%= material.description %></p>
                    </div>
                    <div class="btn-materiais">
                        <%= link_to 'Detalhes', material, :class=> "btn-detalhes" %>
                        <%= link_to 'Baixar', :controller => 'materials', :action => 'download_file', :id => material.id %>
                    </div>
                <% end %>
            </div>
 
          
 
        </div>
    </section>

    <div class="clear"></div>

  <!-- Box do ranking  -->

    <section id="ranking-adm">
        <div class="box-ranking-adm">
         
         
         
          <!--<h3>Ranking das Ejs</h3>-->
          <!--<ol>-->
          <!--  <li>  IN JUNIOR   </li>-->
          <!--  <li>  EJCM   </li>-->
          <!--  <li>  P&Q ENGENHARIA   </li>-->
          <!--</ol>-->
          
        </div>
        <div class="clear"></div>
    </section> 

    <div class="clear"></div>

  <!-- Footer -->


    <footer id="footer">  
      <p>Todos os direitos reservados</p>
      <p>EventIn 2017</p>   
    </footer>
  </section>


















<!--<p id="notice"><%= notice %></p>-->

<!--<p>-->
<!--  <strong>Title:</strong>-->
<!--  <%= @workshop.title %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Description:</strong>-->
<!--  <%= @workshop.description %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Begin time:</strong>-->
<!--  <%= @workshop.begin_time %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Finish time:</strong>-->
<!--  <%= @workshop.finish_time %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Capacity:</strong>-->
<!--  <%= @workshop.capacity %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Occupied:</strong>-->
<!--  <%= @workshop.occupied %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Available:</strong>-->
<!--  <%= @workshop.available %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Local:</strong>-->
<!--  <%= @workshop.local %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Palestrante:</strong>-->
<!--  <%= @workshop.speaker.name %>-->
<!--</p>-->

<!--<% if current_user.admin %>-->
<!--  <%= link_to 'Edit', edit_workshop_path(@workshop) %> |-->
<!--<% end %>-->
<!--<%= link_to 'Back', workshops_path %>-->

<!--<h3>Materials</h3>-->

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Title</th>-->
<!--      <th>Description</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <% @materials.each do |material| %>-->
<!--      <tr>-->
<!--        <td><%= material.title %></td>-->
<!--        <td><%= material.description %></td>-->
<!--        <td><%= link_to 'Detalhes', material %> |</td>-->
<!--        <td><%= link_to 'Baixar', :controller => 'materials', :action => 'download_file', :id => material.id %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
<!--</table>-->