EventIN/config/routes.rb
Rails.application.routes.draw do
  
  # Rotas de Transferencia
  get 'transfers/choice', to: 'transfers#choice', as: :transfer_choice
  post 'choice_create' => 'transfers#choice_create'
  
  # Rotas de Ranking
  get 'federacaos/ranking', to: 'federacaos#ranking', as: :ranking
  get 'ejs/ranking', to: 'ejs#ranking', as: :ranking_ejs
  
  # Rotas de escolha de palestras/workshops
  get 'workshops/choice', to: 'workshops#choice', as: :workshops_choice
  post 'workshops/submit', to: 'workshops#submit', as: :workshops_submit
  
  # Rotas de Materials
  get '/download_file', to: 'materials#download_file', as: :download_file
  
  # Rotas de escolha de quarto
  delete 'rooms/reservation', to: 'rooms#cancel_reservation', as: :cancel_reservation 
  get 'locals/choice', to: 'locals#choice', as: :local_choice
  get 'locals/rooms/:id', to: 'rooms#choice', as: :room_choice
  patch 'users/local/:id', to: 'users#reservate', as: :reservate
  
  # Recuperacao de senha
  get 'users/password_recover', to: 'users#password_recover', as: :password_recover
  post 'users/password_recover', to: 'users#set_password'
  
  resources :transfers
  resources :speakers
  resources :events
  resources :materials
  resources :workshops
  resources :rooms
  resources :locals
  resources :ejs
  resources :federacaos
  #resources :users
  
  
  # Rotas de UserController
  #get 'users/crud', to: 'users#crud', as: :crud
  get 'users', to: 'users#index', as: :users
  get 'users/new', to: 'users#new', as: :user_new
  post 'users/new', to: 'users#create'
  get 'users/:id', to: 'users#show', as: :user
  get 'users/edit/:id', to: 'users#edit', as: :user_edit
  patch 'users/edit/:id', to: 'users#update'
  delete 'users/destroy/:id', to: 'users#destroy', as: :user_destroy
  
  #Rotas de SessionsController
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy', as: :logout

end

EventIN/app/models/ej.rb
class Ej < ApplicationRecord
  belongs_to :federacao
  
  #alias_attribute :ej_name, :name
  #alias_attribute :ej_id, :id
  
  has_many :users, dependent: :destroy
  
end

EventIN/app/models/event.rb
class Event < ApplicationRecord
end

EventIN/app/models/federacao.rb
class Federacao < ApplicationRecord
  
  has_many :ejs;
  
  has_many :users;
  
end

EventIN/app/models/local.rb
class Local < ApplicationRecord
  mount_uploader :photo, PictureUploader
  
  has_many :rooms;
end

EventIN/app/models/material.rb
class Material < ApplicationRecord
  mount_uploader :file, FileUploader
  
  belongs_to :workshop
end

EventIN/app/models/room.rb
class Room < ApplicationRecord
  belongs_to :local
  
  has_many :users;
end

EventIN/app/models/speaker.rb
class Speaker < ApplicationRecord
  mount_uploader :profile_photo, PictureUploader
  
  has_many :workshops
end

EventIN/app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  
  attr_accessor :name, :email, :password, :password_confirmation, :nick, :cel, :cpf,:cep,:ej_id,:cargo_ej,:pos_junior,:federacao_id, :cargo_federacao, :profile_photo
end

EventIN/app/models/user.rb
class User < ApplicationRecord
    mount_uploader :profile_photo, PictureUploader
    
    has_secure_password
    
    belongs_to :ej;
    belongs_to :federacao;
    belongs_to :room, optional: true; #posso criar um usuario antes dele decidir onde vai ficar
    
    has_many :user_workshops, dependent: :destroy; #um usuario pode se inscrever em diversas palestras/workshops 
    has_one :transfer;
    
    validates :name, length: { in: 2..50, presence: true}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, length: { in: 10..50}, format: { with: VALID_EMAIL_REGEX }
    #allow_nil permite que voce nao precise redigitar a senha quando editar o usuario
    validates :password, length: { in: 3..8, presence: true, allow_nil: true }
    validates :nick,  length: { in: 2..50, presence: true}
    
    VALID_CPF_REGEX = /[0-9]{3}.?[0-9]{3}.?[0-9]{3}-?[0-9]{2}/
    validates :cpf, format: { with: VALID_CPF_REGEX }, uniqueness: true
        
    VALID_CEP_REGEX = /[0-9]{2}.?[0-9]{3}-?[0-9]{3}/
    validates :cep, format: { with: VALID_CEP_REGEX }
    
    validate :cpf_format
    validate :cep_format
    
    after_create :deliver_mail
    
    def deliver_mail
        UserMailer.welcome_email(self).deliver_now
    end
    
    #VALID_CEL_REGEX = /[0-9]{2}[0-9]{5}-?[0-9]{4}/
    #validates :cel, format: { with: VALID_CEL_REGEX}
    
    def cpf_format
        cpf.gsub!("-","")
        cpf.gsub!(".","")
    end
    
    def cep_format
        cep.gsub!("-","")
        cep.gsub!(".","")
    end
    
end

EventIN/app/models/user_workshop.rb
class UserWorkshop < ApplicationRecord
  belongs_to :user
  belongs_to :workshop
end

EventIN/app/models/workshop.rb
class Workshop < ApplicationRecord
  belongs_to :speaker #palestrante
  
  has_many :materials
  
  has_many :user_workshops; #uma palestra/workshop pode ter diversos usuarios inscritos
end

EventIN/app/helpers/ejs_helper.rb
module EjsHelper
end

EventIN/app/helpers/events_helper.rb
module EventsHelper
end

EventIN/app/helpers/locals_helper.rb
module LocalsHelper
end

EventIN/app/helpers/materials_helper.rb
module MaterialsHelper
end

EventIN/app/helpers/rooms_helper.rb
module RoomsHelper
end

EventIN/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end 
  
  # Se houver alguem logado, retornara o usuario
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  # Se houver alguem logado, retorna true
  def logged_in?
    !current_user.nil?
  end
  
  # Retira o id do usuario logado do cookie de sessao e limpa o current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Redirecionar para o perfil do Usuario, caso o mesmo já esteja logado
  def logged_user
    if logged_in?
      redirect_to user_path(current_user)
    end
  end
  
  # Redirecionar para a página de login se o user não estiver logado
  def non_logged_user
    if !logged_in?
      redirect_to login_path
    end
  end
  
  # Redireciona caso o usuario nao seja Admin
  def non_admin
      if !current_user
        redirect_to login_path
      end
      if (current_user && !current_user.admin)
        redirect_to user_path(current_user.id)
      end
  end
  

end

EventIN/app/helpers/speakers_helper.rb
module SpeakersHelper
end

EventIN/app/helpers/transfers_helper.rb
module TransfersHelper
end

EventIN/app/helpers/users_helper.rb
module UsersHelper
end

EventIN/app/views/layouts/_messages.html.erb
<!-- Ira exibir os possiveis erros de operacoes do nosso sistema
Cores, :success => verde, :info => azul, :warning => amarelo, :danger => vermelho
-->
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
    <a class="close" data-dismiss="alert">&#215;</a>
  </div>
<% end %>

EventIN/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventIN</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header>
      <div class="topo-menu-temp">
      <%= link_to 'Login', login_path, :class=> "link-home-temp"%>  
      <%= link_to 'Ranking Federação', ranking_path, :class=> "link-home-temp"%>
      <%= link_to 'Ranking EJS', ranking_ejs_path, :class=> "link-home-temp"%>
      <%= link_to 'Quartos Reservados', cancel_reservation_path, :class=> "link-home-temp"%>
      <%= link_to 'Locais Hospedagem', local_choice_path, :class=> "link-home-temp"%>


      <%= link_to 'Eventos', events_path, :class=> "link-home-temp"%>
      <%= link_to 'Novo Evento', new_event_path, :class=> "link-home-temp"%>


      <%= link_to 'Downloads Documentos', materials_path, :class=> "link-home-temp"%>
      <%= link_to 'Criar Documentos', new_material_path, :class=> "link-home-temp"%>


      <%= link_to 'Palestras', workshops_path, :class=> "link-home-temp"%>
      <%= link_to 'Criar Palestras', new_workshop_path, :class=> "link-home-temp"%>


      <%= link_to 'Quartos', rooms_path, :class=> "link-home-temp"%>
      <%= link_to 'Criar Quarto', new_room_path, :class=> "link-home-temp"%>


      <%= link_to 'Hospedagens', locals_path, :class=> "link-home-temp"%>
      <%= link_to 'Nova Hospedagem', new_local_path, :class=> "link-home-temp"%>


      <%= link_to 'EJS', ejs_path, :class=> "link-home-temp"%>
      <%= link_to 'Criar EJS', new_ej_path, :class=> "link-home-temp"%>


      <%= link_to 'Federações', federacaos_path, :class=> "link-home-temp"%>
      <%= link_to 'Criar Federação', new_federacao_path, :class=> "link-home-temp"%>


      <%= link_to 'Usuarios', users_path, :class=> "link-home-temp"%>

      <%= link_to 'Criar Usuarios', users_new_path, :class=> "link-home-temp"%>



      <%= link_to 'Login', login_path, :class=> "link-home-temp"%>

      </div>  
      
      <div class="clear"></div>
      
      <div class="topo-menu">
      <h1> EventIN - IN Junior</h1>
      <!--</div>-->
      <!--<div class="topo-menu">-->
      <%= link_to 'Usuários', users_path %>
      <!--</div>-->
      <!--<div class="topo-menu">-->
      <%= link_to 'Novo Usuário', user_new_path %>
      <!--</div>-->
    </header>

    <% if logged_in?%>
      <div class="topo-menu"><p>Você está logado <%= current_user.name %> <%= link_to "Logout", logout_path, method: :delete %></p></div>
    <% end %>
    
    <%= render 'layouts/messages'%>
    
    <%= yield %>
    
  </body>
</html>